//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestConsoleDemo.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDataType
    {
        public int Id { get; set; }
        public string DataType { get; set; }
        public string DataTypeName { get; set; }
        public int Sort { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateBy { get; set; }
    }
}
